Tools should be placed on a dedicated node
cilium/scaffolding pull request #28
Opened 2022-06-01 22:10 UTC by jtaleric

To reduce noise in the benchmark results we should steer tool pods to a
dedicated node. Currently we use a single node for tools, eventually we
might want to consider having more tool/infra nodes.

In testing we should always deploy at least 3 nodes,
- 1 infra/tool node
- 2 workload nodes

The current scripts still will label a single node even if the user
deploys < 3 nodes.

fixes #27

Signed-off-by: Joe Talerico <rook@isovalent.com>

2022-06-03 20:25 UTC, learnitall commented on group_vars/all
> +tool_label: "scaffolding/app:tools"
Not needed now, but might be nice to split this up into two separate vars:

```yaml
node_role_label: "scaffolding/app"
tool_role_value: "tools"
```

I think this would allow for the labeling feature to scale out a bit more.

2022-06-03 20:25 UTC, learnitall commented on group_vars/all
> +tool_label: "scaffolding/app:tools"
Not needed now, but might be nice to split this up into two separate vars:

```yaml
node_role_label: "scaffolding/app"
tool_role_value: "tools"
```

I think this would allow for the labeling feature to scale out a bit more.

2022-06-03 20:38 UTC, learnitall requested changes
Couple of 'reminder' comments would be great to add in here, and I think there was a variable left in on accident.

2022-06-03 20:38 UTC, learnitall commented on roles/benchmarks/tasks/datapath.yml
> +    register: server_node
Can we add a comment here that these variables are used within the templates? That link is important and would be good to document somewhere for future reference.

2022-06-03 20:38 UTC, learnitall commented on roles/tools/tasks/main.yml
> +    when: apply_tool_label and prom_install.rc == 1
I'm a bit confused as to why `apply_tool_label` is here. Isn't the tool labeling independent of prom? Or are we only installing prom when we can isolate it?

2022-06-03 20:38 UTC, learnitall commented on roles/tools/templates/manager.yml.j2
> +        image: bitnami/redis:6.2.7
This manifest is here to get around the redis bug yeah?

2022-06-04 00:40 UTC, jtaleric commented on roles/tools/templates/manager.yml.j2
> +        image: bitnami/redis:6.2.7
Yup, they have a fix merged now, but they are pointing to latest in a custom image.

2022-06-07 17:52 UTC, merged