Fix License
cilium/scaffolding pull request #51
Opened 2022-08-30 18:21 UTC by jtaleric

Missing date/owner.

Signed-off-by: Joe Talerico (rook) <joe.talerico@gmail.com>

2022-08-30 20:18 UTC, christarazi approved these changes

2022-09-01 15:50 UTC, jtaleric commented
cc @learnitall

2022-09-06 22:55 UTC, learnitall requested changes
I think that this woks for now, but in the future I think it would be best to have the license text verbatim, create an `AUTHORS` file, and add the following header to each source file:

```
Copyright 2022 Authors of scaffolding
SPDX-License-Identifier: Apache-2.0
```

This follows the pattern we already use at Isovalent for adding in a copyright, and will be useful for the more standalone scripts included in the repo.

2022-09-06 22:55 UTC, learnitall commented on LICENSE
>     Licensed under the Apache License, Version 2.0 (the "License");
Can we remove these two lines at the bottom? Without the Appendix they don't have any meaning.

2022-09-30 14:35 UTC, jtaleric commented on LICENSE
>     Licensed under the Apache License, Version 2.0 (the "License");
oh, weird. I rather add the APPENDIX back.. i got too handsy with deleting lines.

2022-09-30 14:36 UTC, jtaleric commented
@learnitall added the appendix back, sorry for the delay didn't see this in my backlog :(

2022-09-30 15:05 UTC, learnitall commented
Hey thank you! No worries on the delay, totally get it.

2022-09-30 15:05 UTC, learnitall approved these changes
LGTM

2022-09-30 15:05 UTC, merged