Add Ron On Node (ron)
cilium/scaffolding pull request #54
Opened 2022-09-09 21:00 UTC by learnitall

Adds  Ron On Node, or, `ron` command within the toolkit. In order to make this happen, some restructuring of the kubernetes-based components of toolkit has been changed, introducing a new 'k8s' package. 

A shell script has also been provided for replicating the same behavior as the ron command, based on https://github.com/alexei-led/nsenter/blob/master/nsenter-node.sh. Ron was added as a command into the toolkit, rather than keeping it as a shell script, to help with debugging and reliability.

With ron we can run profiling tools on nodes as well as any other script we want. For instance, to run the following script on `kind-control-plane`:

```bash
ip a
uname -a
profile 15 > /store/profile.out
```

Use:

```
toolkit ron --pvc --auto-copy -m ./myscript.sh --pod-image my-image-with-bcc /bin/sh /configs/myscript.sh
```

`profile.out` will be placed into a new tarball called `ron.tar.gz` under the working directory toolkit was run from.

To help with creating containers with profiling tools, scripts for creating nix-based images are provided. `bcc.nix` will build a docker image containing bcctools based on the given kernel version.

Todo before merge:

* Update README
* Add nix image with perf

2022-09-09 23:04 UTC, jtaleric reviewed
`Ron was added as a command into the toolkit, rather than keeping it as a shell script, to help with debugging and reliability.` 

From my review, I am not sure how relevant it is maintaining the shell scripts if the plan is to move to ron..

2022-09-09 23:04 UTC, jtaleric commented on scripts/ron.sh
> +NS="${NS:-"default"}"
The manifests do, but the commands to cp,delete,etc are missing `$NS`

2022-09-12 17:58 UTC, christarazi requested changes
:rocket: Looks great, nice work! A few comments below

2022-09-12 17:58 UTC, christarazi commented on scripts/build_nix_image.sh
> +#!/usr/bin/env bash
Nit: A few scripts have `name_with_underscores` and some have `names-with-dashes`, I'd say let's prefer one or the other and be consistent. It seems the latter is used more.

2022-09-12 17:58 UTC, christarazi commented on scripts/get_nsenter_node.sh
> +curl $VERBOSE -LO https://raw.githubusercontent.com/alexei-led/nsenter/master/nsenter-node.sh
Can we just check in a copy of the script without having to fetch it everytime?

2022-09-12 17:58 UTC, christarazi commented on toolkit/cmd/ron.go
> +	"k8s.io/apimachinery/pkg/watch"
In Cilium code, we organize the 3rd party imports as a second group separated by newline and anything from the current repo as a third group. The first group is the std lib.

2022-09-12 17:58 UTC, christarazi commented on toolkit/cmd/ron.go
> +					return false, nil // got a watch event that isn't modified or deleted, continue
I'd suggest breaking out this function into smaller ones so that it's easier to read.

2022-09-12 17:58 UTC, christarazi commented on toolkit/toolkit/k8s/verify.go
> +func DoesContainerStatusShowCompleted(containerStatus map[string]interface{}) (bool, error) {
Why do these helpers are operate on a weakly-typed input? Couldn't these helpers accept a stronger type such as the PodSpec or the ContainerSpec from K8s?

2022-09-12 17:58 UTC, christarazi commented on toolkit/toolkit/k8s/verify.go
> +	ct, err := toolkit.PullStrKey("type", condition)
Re: weak types, it would remove the need for these kinds functions

2022-09-12 19:09 UTC, learnitall commented
@jtaleric That's a good point on the shell script, I'll boot it out.

2022-09-12 19:10 UTC, learnitall commented on scripts/build_nix_image.sh
> +#!/usr/bin/env bash
On it! I'll add a note in the README about this too.

2022-09-12 19:46 UTC, learnitall commented
Just did a force push on the branch to clean up the history a bit (ie remove a commit that was "save in-progress work"), while also removing usage of nix for docker images.

I originally started messing with nix for building our docker images because it was sold as a way to produce fully minimal, reproducible images very quickly. After some more investigation though, it turns out that there is a ton of bloat included in the images I was building with nix. For instance, building an image with bash, coreutils and perf results in an image size of `421MB`. If I want to do the same based on alpine, it's `17.9MB`.

I think that these nix packages are tuned for usability and support rather than being minimal in size. For instance, [perf](https://github.com/NixOS/nixpkgs/blob/nixos-22.05/pkgs/os-specific/linux/kernel/perf.nix#L44) is shipped with some python and perl scripts, so the nix derivation will install python and perl to support running them. Additionally,I'm not sure why, but installing coreutils and bash also puts glibc, gcc, and linux-headers into the container. 

This has some good discussion on the issue: https://fzakaria.com/2021/08/02/a-minimal-nix-shell.html. It includes a technique for visualizing dependencies in the image, so, here is a dependency graph for a container built with coreutils, util-linux, bash and perf:

![out](https://user-images.githubusercontent.com/13142290/189742032-c12e6b9c-8ea7-4ddd-8902-d9bc2d92a8a3.svg)

In the future, I can investigate this further to see if it is possible to build more minimal containers with nix, as I still think nix is a good investment for its features and support. I also think that I may be building the image incorrectly, and using a different approach may work out. Right now though, I'm adding Dockerfiles based on alpine.

2022-09-12 23:03 UTC, learnitall commented on toolkit/toolkit/k8s/verify.go
> +func DoesContainerStatusShowCompleted(containerStatus map[string]interface{}) (bool, error) {
These helpers operate on weakly-typed input because they are targeted towards [Unstructured](https://pkg.go.dev/k8s.io/apimachinery/pkg/apis/meta/v1/unstructured#Unstructured) instances, which are just nested `map[string]interface{}`. I decided to use the less-strongly typed dynamic client, which only returns `Unstructured` structs rather than more strongly typed structs, where available from client-go because it makes writing functions that work across resource types a bit simpler. That's why most of the methods under the `Helper` interface use the dynamic client. A side effect from this is that functions like these need to operate on weakly typed inputs.

I could use some json magic to translate the unstructured input into strong typed inputs, but I figured using [unstructured](https://pkg.go.dev/k8s.io/apimachinery/pkg/apis/meta/v1/unstructured)'s suite of [Nested](https://pkg.go.dev/k8s.io/apimachinery/pkg/apis/meta/v1/unstructured#NestedString)* functions would be more efficient to find and operate on items in the map than doing the translation.

2022-09-12 23:06 UTC, learnitall commented on toolkit/toolkit/k8s/verify.go
> +	ct, err := toolkit.PullStrKey("type", condition)
For stuff like `DoesContainerStatusShowCompleted` I agree with you that using stronger types would remove the need, but this function would still need to exist regardless. `DoesContainerStatusShowCompleted` just checks if the map has `state.terminated.reason` and if it is equal to `Completed`. `DoesConditionShowReady` uses a switch statement to ensure that the right condition type is compared to the right boolean value, since some conditions are 'good' when their status is false (ie `PIDPressure`), while others are good if their status is true (ie `Ready`).

2022-09-12 23:13 UTC, learnitall commented on scripts/get_nsenter_node.sh
> +curl $VERBOSE -LO https://raw.githubusercontent.com/alexei-led/nsenter/master/nsenter-node.sh
Done :+1:

2022-09-12 23:19 UTC, christarazi commented on toolkit/toolkit/k8s/verify.go
> +func DoesContainerStatusShowCompleted(containerStatus map[string]interface{}) (bool, error) {
I think this is fine if we believe that the pros of using unstructured outweighs the cons which includes weak types. My concern was that during development we don't want to spend too much time inventing new helpers when they already exist by virtue of using stronger types and the helpers they come with. Additionally, it can be error-prone to use weak types, but as long as the code is simple enough and we don't expect this code to change much going forward, then maybe this is no longer a concern.

2022-09-12 23:22 UTC, christarazi commented
> In the future, I can investigate this further to see if it is possible to build more minimal containers with nix, as I still think nix is a good investment for its features and support. I also think that I may be building the image incorrectly, and using a different approach may work out. Right now though, I'm adding Dockerfiles based on alpine.

I agree with deferring the optimization of images to the future. For now, using alpine based images is fine with me. :+1:

2022-09-12 23:24 UTC, learnitall commented on toolkit/cmd/ron.go
> +	"k8s.io/apimachinery/pkg/watch"
Changed. Most source files needed this change.

2022-09-13 00:37 UTC, learnitall commented on toolkit/toolkit/k8s/verify.go
> +func DoesContainerStatusShowCompleted(containerStatus map[string]interface{}) (bool, error) {
Yeah that makes sense. Thank you for bringing this up, it did need to be talked about. I tried to add runtime error-checking for weak types where appropriate to try to address this, but it's a pain to test at runtime. I think the code is simple enough for now that we can get away with this. But, I am struggling with understanding the balance between writing strong-typed functions for each type, versus taking advantage of weak-types to reduce boilerplate.

2022-09-13 03:40 UTC, christarazi commented on toolkit/toolkit/k8s/verify.go
> +func DoesContainerStatusShowCompleted(containerStatus map[string]interface{}) (bool, error) {
@learnitall No need to worry about it now. It can be something we can clean up later. Better to get something out of the door working rather than make it perfect and never ship it :)

2022-09-13 17:51 UTC, learnitall commented on toolkit/toolkit/k8s/verify.go
> +func DoesContainerStatusShowCompleted(containerStatus map[string]interface{}) (bool, error) {
Good point hah, I'll just add a note into the backlog about it

2022-09-13 19:28 UTC, learnitall commented on scripts/get_nsenter_node.sh
> +curl $VERBOSE -LO https://raw.githubusercontent.com/alexei-led/nsenter/master/nsenter-node.sh
After discussion, going to actually remove this script from the repo. Useful for debugging interactively on a node, but the GPLv2 license adds a conflict

2022-09-13 19:35 UTC, learnitall commented
Did a couple of more force pushes to clean up the history. We should be LGTM.

2022-09-14 00:52 UTC, christarazi approved these changes

2022-09-14 15:46 UTC, merged