Improve Helper Usability and Error Handling
cilium/scaffolding pull request #75
Opened 2023-03-30 18:25 UTC by learnitall

Two changes in this PR:

* Modify the Helper's WaitOnWatchedResource to use k8s client-go's watch tools. This function essentially did the same thing as client-go's [watch.Until](https://pkg.go.dev/k8s.io/client-go@v0.26.3/tools/watch#Until) function, so I gutted WaitOnWatchResource to use [watch.UntilWithSync](https://pkg.go.dev/k8s.io/client-go@v0.26.3/tools/watch#UntilWithSync), which has great error handling. This way we don't have to maintain a tool that already exists.
* Removed Ctx from the Helper, so users can pass their own context into each function as needed.

These are breaking changes.

2023-03-30 19:02 UTC, thorn3r approved these changes
looks great! nice find on the watchtools :+1:

2023-03-31 11:18 UTC, marseel requested changes
Looks good, nice improvements, thanks :+1: 

Just small nits and one leaking goroutine

2023-03-31 11:18 UTC, marseel commented on toolkit/toolkit/k8s/helper.go
> +			checkCtx, gvr, ns, NewFieldSelectorFromName(name), "",
Maybe it would make sense to log `err` here?
For example, we get some error, but we still send "true" to "checkDone".

2023-03-31 11:18 UTC, marseel commented on toolkit/toolkit/k8s/helper.go
>  	checkDone := make(chan bool)
We should increase default size of channel to 1. If `doDelete` gets error it will not wait on channel and `doCheck` goroutine will get stuck in writing to channel.

2023-03-31 11:18 UTC, marseel commented on toolkit/toolkit/k8s/helper.go
> +			checkCtx, gvr, ns, NewFieldSelectorFromName(name), "",
Even better would be to send err through the channel so we can return it from `DeleteResourceAndWaitGone`

2023-03-31 15:07 UTC, learnitall commented
Pushed a fix for your comments @marseel, do you mind taking another look?

2023-03-31 15:08 UTC, learnitall commented on toolkit/toolkit/k8s/helper.go
>  	defer cancelCheck()
Ah good point, removed :+1:

2023-03-31 15:08 UTC, learnitall commented on toolkit/toolkit/k8s/helper.go
> +			checkCtx, gvr, ns, NewFieldSelectorFromName(name), "",
Done :+1:

2023-03-31 15:08 UTC, learnitall commented on toolkit/toolkit/k8s/helper.go
>  	checkDone := make(chan bool)
Good catch! Done :+1:

2023-03-31 15:14 UTC, marseel commented on toolkit/toolkit/k8s/helper.go
> +	err = <-checkDone
nit: just `return <-checkDone` here is fine :)

2023-03-31 15:16 UTC, marseel approved these changes

2023-03-31 15:17 UTC, merged