Add GHA workflows to build and lint the cmapisrv-mock
cilium/scaffolding pull request #85
Opened 2024-06-25 16:42 UTC by giorio94

2024-06-26 14:09 UTC, aanm requested changes

2024-06-26 14:09 UTC, aanm commented on .github/workflows/build.yaml
> +          username: ${{ secrets.QUAY_USERNAME_USERNAME }}
```suggestion
          username: ${{ secrets.QUAY_USERNAME_SCAFFOLDING }}
```

2024-06-26 14:09 UTC, aanm commented on .github/workflows/build.yaml
> +          password: ${{ secrets.QUAY_PASSWORD_PASSWORD }}
```suggestion
          username: ${{ secrets.QUAY_PASSWORD_SCAFFOLDING }}
```

2024-06-26 14:26 UTC, giorio94 commented
Successful run with image push: https://github.com/cilium/scaffolding/actions/runs/9681290574/job/26711523516?pr=85

2024-06-27 10:59 UTC, aanm approved these changes

2024-06-27 10:59 UTC, merged